apiVersion: v1
kind: Namespace
metadata:
  name: dev-example #nombre del namespace CAMBIAR

---
#Limita al namespace
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    name: pods-high
    namespace: dev-example #nombre del namespace CAMBIAR
  spec:
    hard:
      requests.cpu: "1000" #1k es un cpu
      requests.memory: 1Gi
      limits.cpu: "2000"
      limits.memory: 1Gi
      #pods: "10"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxdeployment
  namespace: dev-example #nombre del namespace CAMBIAR
  labels:
    app: label-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: label-deployment
  template:
    metadata:
      labels:
        app: label-deployment
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
      
---
kind: Service
apiVersion: v1
metadata:
  name:  test-service
  namespace: dev-example #nombre del namespace CAMBIAR
spec:
  selector:
    app: label-deployment #label match del servicio
  type:  NodePort #LoadBalancer | ClusterIP | NodePort
  ports:
  - protocol: TCP
    port:  8090
    targetPort:  80 #puerto del contenedor, si fuera una img hecha por mi seria el de expose


